### ISSUE TITLE
Zodiac Safe App sends Delay transaction to the safe address instead of the modifier address

### ISSUE THREAD

**Issue by de33** [gnosis/zodiac-safe-app#66]
Delay transactions sent through the Zodiac UI seem to always fail with "Module not authorized", and when you look up the transaction on Etherscan you can clearly see the transactions are sent to the Safe rather than the Delay modifier itself. 

I am an experienced delay modifier user who has no problem setting up delay modifiers and delay transactions and then executing them through scripts so I am familiar with the flow.

This transaction was done through the Zodiac UI 
https://etherscan.io/tx/0xf20baeee1024444cc106d2de287c9f1484f94c515acb503d0bfcd4075a25109b

**Comment by auryn-macmillan** [comment]
When you interact with a module via the Zodiac safe app, you are triggering transactions to modules from the safe, rather than from an address that is connected to the delay modifier as a module.

If your connected account is an EOA, then probably etherscan is the best option. If it's a safe, then the transaction builder safe app is the best option.
